-- server/db.sql
CREATE DATABASE IF NOT EXISTS mg_db;
USE mg_db;

CREATE TABLE IF NOT EXISTS highscores (
  username VARCHAR(50) PRIMARY KEY,
  score INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX(score)
);

CREATE TABLE IF NOT EXISTS users (
  username VARCHAR(50) PRIMARY KEY,
  password VARCHAR(255) NOT NULL
);  